# Создайте/обновите файл: netlify.toml в корне проекта

[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Настройки функций
[functions]
  directory = "netlify/functions/"
  included_files = ["netlify/functions/**"]
  node_bundler = "esbuild"

# Настройки для SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Перенаправления для React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["!robot"]}

# Настройки безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Настройки для API функций
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Кэширование статических ресурсов
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge Functions для автоматического обновления кеша
[[edge_functions]]
  path = "/.netlify/edge-functions/auto-update-cache"
  function = "auto-update-cache"

# Настройки для Scheduled Functions (если поддерживаются)
[functions."auto-update-cache"]
  schedule = "0 1 * * *"
  # 04:00 по Киеву (зимнее время) = 01:00 UTC
  # 04:00 по Киеву (летнее время) = 01:00 UTC (автоматически корректируется)

# Настройки для разработки
[dev]
  command = "npm start"
  port = 3000
  autoLaunch = false
  functions = "netlify/functions"

  # Переменные окружения для продакшена (переопределяются через Netlify UI)
[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_ENV = "production"

# Переменные для разработки
[context.dev.environment]
  NODE_ENV = "development"
  REACT_APP_ENV = "development"

# Настройки для функций
[functions.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

# Переменные окружения для функций (будут использоваться если не заданы в Netlify UI)
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Таймауты для функций (максимум 26 секунд на бесплатном плане)
[functions]
  external_node_modules = ["@supabase/supabase-js"]
